---
  root: true
  env:
    es6: true
    node: true
  extends:
    eslint:recommended
  rules:
    no-unused-vars:
      - error
      - argsIgnorePattern: ^_ # allows omission and can increase clarity/debugging
    semi:
      - error
      - never # lee prefers
    comma-dangle:
      - error
      - always-multiline # josi prefers
